### ISSUE TITLE
Gain per source?

### ISSUE THREAD

**Issue by ghost** [DanielRudrich/ABComparisonPlugin#7]
Suggestion: can a gain be added for each source? A/B comparison doesn't work if one source is louder than the other (the loudest always "sound better"...)

**Comment by juhanipaasonen** [comment]
Is there a particular reason the gains should be controlled by ABComparison instead of the DAW you're using? The channel sliders do just that. In general I find it easier and less error prone to normalise the audio files somewhere else.

**Comment by DanielRudrich** [comment]
I thought about adding this feature to also apply gains to the single streams, especially as the fades are implemented using gain objects. However, I wasn't sure if the interface would become too crowded with an additional setting. Even if hidden, it might be not obvious that the gain is adjusted by the plug-in. Something I would definitely set and forget...

So controlling it via Channel Volume Sliders (like in Reaper, combined with configured parent channels) seems to be quite easy. There are also handy plug-ins like mcfx_gain [https://github.com/kronihias/mcfx](https://github.com/kronihias/mcfx), to apply individual gains within one multi-channel bus.

**Comment by ghost** [comment]
My use case is different: without a DAW, not editing audio streams, just listening to them.
